#100 HackerRank | Algorithms > Strings > Two Characters
fedotkin/dotnet pull request #101
Opened 2023-11-20 13:05 UTC by fedotkin

Task [Two Characters](https://www.hackerrank.com/challenges/two-characters/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-11-20 13:07 UTC, fedotkin commented
hackerrank-100! 💯

2023-11-21 15:23 UTC, raman-m commented
Віншую з Сотачкай! 😉

2023-11-21 15:36 UTC, raman-m requested changes
Жэстачайшы алгарытм! 💥

2023-11-21 15:36 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/TwoCharacters.cs
> +        }
Вышэй: 
`using System.Linq`
і ніжэй:
```suggestion
        var symbols = s.Distinct().ToList(); // General list of all existing symbols in string "s"
```

2023-11-23 10:19 UTC, fedotkin commented
Задачка таксама жэстачайшая)
Сярод хакерранкавых джунау 20% не змаглі вырашыць наогул.

2023-11-25 10:58 UTC, merged