#102 HackerRank | Algorithms > Strings > CamelCase
fedotkin/dotnet pull request #103
Opened 2023-11-27 08:00 UTC by fedotkin

Task [CamelCase](https://www.hackerrank.com/challenges/camelcase/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-11-27 08:01 UTC, fedotkin commented
Для панядзелка возьмем прасцей задачку)

2023-11-28 16:51 UTC, raman-m requested changes

2023-11-28 16:51 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/CamelCase.cs
> +        }
```suggestion
        int result = s.Count(ch => char.IsUpper(ch)); // LINQ to Objects
```
або нават так
```csharp
int result = s.Count(char.IsUpper);
```
Патлумачыць?

2023-11-29 06:56 UTC, fedotkin commented
Агонь! Для атрымання колькасці элементау выкарыстоуваецца метад Count(), які прымае лямбда-выраз з умовай 👍

2023-11-29 09:19 UTC, raman-m commented
> які прымае лямбда-выраз з умовай

...які прымае аргумент, які ёсць прэдыкат.

Прэдыкат - гэта функцыя (метад) які прымае аргументам ітэратыўны элемент, а вяртае `bool`: `true` або `false`.
Як выглядае дэлегат прэдыката: `Func<TSource, bool>`, дзе `TSource` - гэта тып элемента інумератара, а `bool` - тып значэння, які вяртаецца, а `Func` - гэта функцыянальны дэлегат, які вяртае нейкае значэнне.

Азначэнне (сігнатура) дапаможнага LINQ-метада `Count`:
```c#
public static int Count<TSource> (this System.Collections.Generic.IEnumerable<TSource> source, Func<TSource,bool> predicate);
```
Дакументацыя СіШарпа і дапаможнай бібліятэкі-класа `Enumerable`: [Enumerable.Count<TSource>(IEnumerable<TSource>, Func<TSource,Boolean>)](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count?view=net-8.0#system-linq-enumerable-count-1(system-collections-generic-ienumerable((-0))-system-func((-0-system-boolean))))

Вучы СіШарп, джун!

2023-11-29 09:22 UTC, raman-m requested changes
Адшліфуемся?

2023-11-29 09:22 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/CamelCase.cs
> +        return result;
```suggestion
        return string.IsNullOrEmpty(s) ? 0
            : s.Count(char.IsUpper) + 1;
```
А чаму + 1 ?

2023-11-29 10:32 UTC, fedotkin commented
+1, таму што на Хакеранке усе тэсты пачынаюцца з маленькай літары

2023-11-29 10:50 UTC, raman-m approved these changes

2023-11-29 10:53 UTC, merged