#104 HackerRank | Algorithms > Implementation > The Time in Words
fedotkin/dotnet pull request #105
Opened 2023-11-30 10:36 UTC by fedotkin

Task [The Time in Words](https://www.hackerrank.com/challenges/the-time-in-words/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-11-30 11:51 UTC, raman-m requested changes
Аптымізацый амаль няма.
І выкарыстанне рэкурсіі - гэта добра.

2023-11-30 11:51 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/TheTimeInWords.cs
> +        else if (1 < m & m < 30)
```suggestion
        else if (1 < m && m < 30)
```
Розніцу паміж `&` ды `&&` разумееш?

2023-11-30 11:51 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/TheTimeInWords.cs
> +        else if (30 < m & m < 60)
```suggestion
        else if (30 < m && m < 60)
```

2023-11-30 11:58 UTC, raman-m requested changes

2023-12-01 06:39 UTC, fedotkin commented on hackerrank/src/Algorithms/Implementation/TheTimeInWords.cs
> +        else if (1 < m & m < 30)
Праверка другой умовы не праводзіцца, калі вынік першай умовы - false

2023-12-02 14:49 UTC, raman-m approved these changes

2023-12-02 14:51 UTC, merged