#17 Single responsibility in the Program class
fedotkin/dotnet pull request #20
Opened 2022-11-25 13:09 UTC by fedotkin

2022-11-26 16:24 UTC, raman-m requested changes
Fix the issues 👇! 🙏 
And, add the readme-file for the Exercise 1. I suggest name it as **Exercise1.md**

2022-11-26 16:24 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/Chapter5.cs
> +        //метод Run (вызывает демонстрацию класса Exercise1.cs)
1️⃣  Do NOT use Russian! Use English texts instead.

2️⃣  Use developer's docs aka XML-docs inside of C# code.
Read & Learn: [XML documentation comments - document APIs using /// comments | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/)
Hope this code is a good XML-doc for the **Run** method:
```csharp
/// <summary>
///  метод Run (вызывает демонстрацию класса Exercise1.cs).
/// </summary>
public static void Run() {}
```

2022-11-26 16:24 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +﻿namespace ChapterExercises._5_interfaces_and_contracts
### ${\color{red}Wrong\ namespace!}$
The `Chapter5` sub-namespace should be defined!

2022-11-26 16:24 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +    }*/
I would prefer to uncomment these lines of the **IA** interface. Uncommenting will not break something.

2022-11-26 16:24 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +    }
The class is empty! Why not make it static? Why not to move all demo classes to the `Exercise1` class. So, doing that we make sub-classes, this is another emulation of sub-namespaces. 😊

2022-11-26 16:24 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +        void IB.MethodA() => Console.WriteLine("pip_2");
### ${\color{orange}Multiple\ coding\ styles\!}$
For the **MethodA** method you use classic method body definition via braces `{}`.
But for the **IB.MethodA** method you use expression body definition via arrow operator `=>`.

Choose your favorite coding style, and make both definitions the same.

2022-12-07 07:52 UTC, fedotkin commented on trey-nash/Program.cs
> +            int num = Convert.ToInt32(Console.ReadLine());
If you remove condition `while (!num)` and leave the blocks `try` `catch`, then everything works (otherwise error).
What is condition `while (!num)` for?
```csharp
int chapterNo = 0;
try { chapterNo = Convert.ToInt32(Console.ReadLine()); }
catch { chapterNo = 0; }
```

2022-12-07 07:52 UTC, fedotkin commented on trey-nash/Program.cs
> +        }
fixed

2022-12-07 07:56 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Chapter5.cs
> +﻿namespace ChapterExercises._5_interfaces_and_contracts
fixed

2022-12-07 08:19 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Chapter5.cs
> +        //метод Run (вызывает демонстрацию класса Exercise1.cs)
fixed

2022-12-07 08:20 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +﻿namespace ChapterExercises._5_interfaces_and_contracts
fixed

2022-12-07 08:22 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +    }*/
fixed

2022-12-07 08:27 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +        void IB.MethodA() => Console.WriteLine("pip_2");
What is your favorite coding style?

2022-12-07 08:47 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/Exercise1.cs
> +    }
fixed

2022-12-08 14:50 UTC, closed without merging

2022-12-09 13:46 UTC, raman-m commented on trey-nash/Program.cs
> +﻿using ChapterExercises._5_interfaces_and_contracts;
I'm OK with this namespace name! Go ahead and fix!

2022-12-09 13:48 UTC, raman-m commented on trey-nash/Program.cs
> +            int num = Convert.ToInt32(Console.ReadLine());
Sorry, my fault!
For C# you need this code:
```csharp
int num = 0;
while (num == 0)
{
    try { num = Convert.ToInt32(Console.ReadLine()); }
    catch { num = 0; }
}
```