Paint "Hello World!" as ASCII art
fedotkin/dotnet pull request #33
Opened 2022-12-29 12:16 UTC by fedotkin

### These tasks are done:
1. Generate 1st "Hello World" art, save to a text file.
  Read the art from the file and print it to the console.
2. Generate 2nd "Hello World" art. Compress it to a string stream by the rule: `AAA` -> `3A`.
  Decompress the art and print it to the console.

2023-01-03 12:04 UTC, raman-m requested changes
Please fix all bugs and issues!

The main problem of this code that there are no unit tests.
It is impossible to check correctness of algorithm implementation!

Also the readability of the code is low!
It is hard to understand the code because of too long bodies and blocks.
Please remove all code smells too!

2023-01-04 10:25 UTC, fedotkin commented on trey-nash/Usings.cs
> +global using System.IO;
fixed

2023-01-04 10:25 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +﻿using Fedotkin.Dotnet.TreyNash.Ch5_InterfacesAndContracts;
fixed

2023-01-04 11:36 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +        Console.Write("Enter task number of Exercise1 (1-2): ");
$\color{MediumSeaGreen}{\textbf{Fixed in part}}$
(no Exercise1 file)

2023-01-04 11:46 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +        string filename = @"..\..\..\1-c#-preview\Exercise1_1.txt";
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 12:17 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +        start_list.Add(@"
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 12:51 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +    public static void Task1()
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 12:52 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +    /// </summary>
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 12:56 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +        foreach (var item in decompressed_list) Console.WriteLine(item);
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 12:58 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_1.cs
> +static class Exercise1_1
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 13:00 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_1.cs
> +    /// Stream from text file
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 13:08 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_1.cs
> +        StreamReader reader = new StreamReader(filename);
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 13:15 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_1.cs
> +        reader.Close();
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 13:16 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +﻿namespace Fedotkin.Dotnet.TreyNash.Ch1_CSharpPreview;
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 13:25 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    public static List<string> Сompression(List<string> input_list)
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-04 16:11 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +    /// Runs the demo of <see cref="Exercise1"/>.
**Not fixed!**
I don't see the `Exercise1` class! Where is it?

2023-01-04 16:21 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +        string filename = @"..\..\..\1-c#-preview\Exercise1_1.txt";
### ${\color{red}Not\ fixed!}$
The path to the file is still hardcoded!!! Are you sure that after compilation or copying the console.exe the app will be able to find and open the file?
Do you understand the term "**hardcoded**"?
Hardcoded data in source code is bad thing. File data should be configurable, discoverable or read from a folder.
You have ignored the requirements of the fix! That's bad!

2023-01-04 16:35 UTC, raman-m commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +static class Exercise1_2
### ${\color{orange}Fixed\ partially!}$
You have to define 2 classes: `Exercise1` and `TextCompression`

2023-01-06 11:34 UTC, fedotkin commented on trey-nash/1-c#-preview/Chapter1.cs
> +        string filename = @"..\..\..\1-c#-preview\Exercise1_1.txt";
$\color{MediumSeaGreen}{\textbf{Fixed 2}}$

2023-01-06 14:34 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +static class Chapter1
Please, fix it!
The `Chapter1` class is still defined in the namespace '**.Ch1_CSharpPreview;**' !
It should be defined in root namespace, see below:
```csharp
namespace Fedotkin.Dotnet.TreyNash;
````

2023-01-06 14:38 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +    /// Runs the demo of <see cref="Exercise1"/>.
Please, define an `Exercise1` class in **Exercise1.cs** file!
After that, define the `TextCompression` class in the `Exercise1` class as subclass.
Or, define  the `TextCompression` class in separate **TextCompression.cs** file. It is up to you!

2023-01-06 14:41 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +    public static void Task1()
It's duplicate of previous issue: https://github.com/fedotkin/dotnet/pull/33#discussion_r1063487032
Going to close this !

2023-01-06 14:43 UTC, raman-m commented on trey-nash/1-c#-preview/Chapter1.cs
> +        string filename = @"..\..\..\1-c#-preview\Exercise1_1.txt";
I see, it is fixed in commit [Added Exercise1.txt file](https://github.com/fedotkin/dotnet/pull/33/commits/08686e13796a6c1c071cac01db8a72e4beae7783)

Thank you!

2023-01-06 14:48 UTC, raman-m commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +static class Exercise1_2
This comment is duplicate of [Exercise1 class](https://github.com/fedotkin/dotnet/pull/33#discussion_r1063487032)
Closing...

2023-01-06 14:53 UTC, raman-m commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
Please, remove this method in the future while refactoring the `TextCompression` class to move **Addition** code to atomic Rule-like methods.
Note, that there is no need to incapsulate string concatenation to separate method. Just keep the string concatenation inside of Rule-method.

2023-01-06 15:04 UTC, raman-m commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
1. I am going to write some unit tests to check that you have implemented all compression rules in this method.
But... Please, split the **Compress** method to atomic Rule-like methods.

2. **For**-loop usage!
```csharp
for (int i = 0; i < input_list.Count; i++) //Compress each line in the list
{
    int position = 0;
    char symbol = inputList[i][position];
    // ...
}
```
Have you heard about **foreach**-loop statement for an `IEnumerable` objects?
See how your code can become more elegant:
```csharp
foreach (string line in input_list)
{
    int position = 0;
    char symbol = line[position];
    // usage of the 'line' variable...
}
```

2023-01-06 15:07 UTC, raman-m commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
Refactor your code using **foreach** instead of **for** loop statement!
```csharp
for (int i = 0; i < input_list.Count; i++) //Compress each line in the list
{
    int position = 0;
    char symbol = inputList[i][position];
    // ...
}
```
Have you heard about **foreach**-loop statement for an `IEnumerable` objects?
See how your code can become more elegant:
```csharp
foreach (string line in input_list)
{
    int position = 0;
    char symbol = line[position];
    // usage of the 'line' variable...
}
```

2023-01-06 15:10 UTC, raman-m commented on trey-nash/Program.cs
> +using Fedotkin.Dotnet.TreyNash.Ch5_InterfacesAndContracts;
Please, fix it after fixing of [Chapter1 namespace issue](https://github.com/fedotkin/dotnet/pull/33#discussion_r1063483617).

2023-01-09 08:22 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
$\color{MediumSeaGreen}{\textbf{part 2: Fixed}}$

2023-01-09 08:29 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
$\color{MediumSeaGreen}{\textbf{foreach-loop: Fixed}}$

2023-01-10 08:23 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1_2.cs
> +    }
$\color{MediumSeaGreen}{\textbf{String concatenation operator: Fixed}}$

$\color{MediumSeaGreen}{\textbf{Remove Addition method: Fixed}}$

2023-01-10 12:03 UTC, raman-m requested changes
### ${\color{orange}There\ are\ no\ unit\ tests\ for\ the\ 'TextCompression'\ class!}$
At this moment, it is impossible to check correctness of the implementation in the `TextCompression` class! Write unit tests for methods:
- TextReads
- Compress
- Decompress

aka the `ITextCompression` interface.

2023-01-25 13:01 UTC, fedotkin commented on trey-nash/1-c#-preview/Exercise1.cs
> +    public class TextCompression : ITextCompression
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-01-26 13:50 UTC, raman-m approved these changes
Confirmed that all unit tests are $\large{\color{green}green}$. Congrats! 🎉 

$\large{\color{green}Approved}$

⚠️  Use classic "**Merge pr**" option.

2023-01-26 13:58 UTC, merged