#39 HackerRank | Algorithms > Implementation > Cats and a Mouse
fedotkin/dotnet pull request #41
Opened 2023-01-31 13:08 UTC by fedotkin

Tested [Cats and a Mouse](https://www.hackerrank.com/challenges/cats-and-a-mouse/submissions/code/312067861)

2023-01-31 13:31 UTC, raman-m requested changes
$\large{\color{red}Wrong\ solution\ structure\ of\ folders!}$
Move solution to **../hackerrank** in the root repo folder!

1. Create **hackerrank** folder in the root
2. Move **sln**-file to **hackerrank** folder
3. Create **src** and **test** folders in the **hackerrank** folder
4. Move all HackerRankChallenge files to **src** folder
5. Rename HackerRankChallenge.csproj to HackerRank.csproj
6. Move all HackerRankChallenge.Tests files to **test** folders
7. Rename HackerRankChallenge.Tests.csproj to HackerRank.Tests.csproj
8. Create **Algorithms\Implementation** folder in **src** folder
9. Move CatsAndMouse.cs file to the **Algorithms\Implementation** folder
10. Do the same of 8-9 for test class CatsAndMouseTests.cs

"src vs test" couple is standard and best practice for dotnet solutions.

2023-02-01 09:12 UTC, raman-m requested changes
Please fix these bugs!

2023-02-01 09:12 UTC, raman-m commented on hackerrank/test/Algorithms/Implementation/CatsAndMouseTest.cs
> +    public void Add_MultipleNumbers_ReturnText(string input, string expected)
$\large{\color{red}Wrong\ method\ name!}$
This name of the method does not readable. It does not provide much info about the target of testing!
You forgot best practices from Workshop 2 where explained that:
> Every unit test method name should have the pattern:  SutName_Condition_Result


You test `catsAndMouse` method and condition is Problem requirements as Example and Sample cases. The result "FeatureWorksFine".
But because you have joined all initial cases into the one unit test I think it is fitness tests for the feature. So, the method could have this name:
```csharp
public void CatsAndMouse_Fitness_Test(string input, string expected)
{ }
```

2023-02-01 13:24 UTC, fedotkin commented on hackerrank/src/HackerRank.csproj
> +    <Nullable>enable</Nullable>
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-02-01 13:24 UTC, fedotkin commented on hackerrank/test/HackerRank.Tests.csproj
> +    <Nullable>enable</Nullable>
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-02-01 13:24 UTC, fedotkin commented on hackerrank/test/Algorithms/Implementation/CatsAndMouseTest.cs
> +namespace Fedotkin.Dotnet.HackerRank.Tests;
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-02-01 13:24 UTC, fedotkin commented on hackerrank/test/Algorithms/Implementation/CatsAndMouseTest.cs
> +    public void Add_MultipleNumbers_ReturnText(string input, string expected)
$\color{MediumSeaGreen}{\textbf{Fixed}}$

2023-02-02 16:27 UTC, fedotkin commented
Issue closed, done in PR #46

2023-02-02 16:27 UTC, closed without merging