#56 HackerRank | Algorithms > Sorting > Insertion Sort - Part 1
fedotkin/dotnet pull request #57
Opened 2023-02-17 13:11 UTC by fedotkin

Tested [Insertion Sort - Part 1](https://www.hackerrank.com/challenges/insertionsort1/submissions/code/314858790)

2023-02-20 09:33 UTC, raman-m requested changes
Fix issues please!

2023-02-20 09:33 UTC, raman-m commented on hackerrank/test/Algorithms/Sorting/InsertionSortPart1_ResultTests.cs
> +        string filePath = Path.Combine(dir, nameof(InsertionSort1_Example_PrintedArrays) + ".txt");
For unit tests it does not matter the real folder of reading/writing streams.
So, you can use `Environment.CurrentDirectory` property without problems.

2023-02-20 09:33 UTC, raman-m commented on hackerrank/test/Algorithms/Sorting/InsertionSortPart1_ResultTests.cs
> +        string filePath = Path.Combine(dir, nameof(InsertionSort1_Sample_PrintedArrays) + ".txt");
```diff
- Don't use assembly-related operations inside of unit test! 
```

2023-02-20 12:43 UTC, fedotkin commented on hackerrank/src/Algorithms/Sorting/InsertionSortPart1.cs
> +        }
Well, also `index` and `movingElement` variables work only in the loop, but they are also necessary after the loop for the correct termination of the program. 
For example, input: `10, [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 1 ]`

2023-02-20 13:55 UTC, raman-m commented on hackerrank/src/Algorithms/Sorting/InsertionSortPart1.cs
> +        }
The `i` and `movingElement` variables will be visible after **for**-loop also.

2023-02-20 14:48 UTC, fedotkin commented on hackerrank/src/Algorithms/Sorting/InsertionSortPart1.cs
> +        }
`i` variable is also needed outside of the loop

2023-02-20 14:56 UTC, fedotkin commented on hackerrank/src/Algorithms/Sorting/InsertionSortPart1.cs
> +        }
sorry, the code doesn't work

2023-02-21 11:12 UTC, raman-m commented on hackerrank/src/Algorithms/Sorting/InsertionSortPart1.cs
> +        }
You need to explain shortly why it doesn't work!
To extand the scope of the `index` and `movingElement` variables out from the **for**-loop scope you can apply the short declaration life hack. It allows to make `index` and `movingElement` visible in whole scope of the method.
```csharp
int index = 0, movingElement = 0; // life hack!
for (index = n - 1, movingElement = arr[index]; // initialization
    index > 0 && arr[index - 1] > movingElement; // condition
    index--) // iteration
//for (index = n - 1, movingElement = arr[index]; index > 0 && arr[index-1] > movingElement; index--)
{
    arr[index] = arr[index - 1];
    Console.WriteLine(string.Join(" ", arr));
}
arr[index] = movingElement;
Console.WriteLine(string.Join(" ", arr));
```
This is your algorithm based on **for**-loop.
Enjoy!

2023-02-21 11:13 UTC, raman-m approved these changes
```diff
+ Approved
```

2023-02-27 10:24 UTC, merged