Feature/1
fedotkin/dotnet pull request #7
Opened 2022-10-26 12:20 UTC by fedotkin

**Create folder structure and README.md file.**

2022-10-26 12:23 UTC, fedotkin commented
I propose to create a two-digit numbering for a beautiful order (01, 02...)

2022-10-26 15:42 UTC, raman-m approved these changes
Great job! But there are issues to fix in TOC (Оглавление).

2022-10-26 15:42 UTC, raman-m commented on trey-nash/12-threading-in-c#/README.md
> +- Использование ThreadPool
You forgot about the section "Synchronizing Work Between Threads"!
This is "**Синхронизация работы между потоками**" in Russian.

2022-10-26 15:42 UTC, raman-m commented on trey-nash/17-dynamic-types/README.md
> +- Резюме
You forgot about the section "ExpandoObject: Creating Objects Dynamically"!
This is "**Динамическое создание объектов с помощью ExpandoObject**" in Russian.

2022-10-26 15:42 UTC, raman-m commented on trey-nash/3-c#-syntax-overview/README.md
> +- Пространства имен
Why not '**ё**'?
`имён`

2022-10-26 15:42 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/README.md
> +# Chapter 5. Interfaces and contracts[^1]
`Chapter 5:`  ???

2022-10-26 15:42 UTC, raman-m commented on trey-nash/6-overloading-operators/README.md
> +- Типы и форматы перегруженных операций
Забыл про параграф: "Можете - не значит должны"

2022-10-26 15:42 UTC, raman-m commented on trey-nash/7-exception-handling-and-exception-safety/README.md
> +- Обеспечение нейтральности к исключениям
Забыл два параграфа для страниц 199 и 200, перед "Обеспечение нейтральности..."

2022-10-26 15:49 UTC, raman-m requested changes
Sorry, you need to fix the issues.

2022-10-27 06:40 UTC, fedotkin commented on trey-nash/12-threading-in-c#/README.md
> +- Использование ThreadPool
fixed

2022-10-27 06:43 UTC, fedotkin commented on trey-nash/17-dynamic-types/README.md
> +- Резюме
fixed

2022-10-27 06:47 UTC, fedotkin commented on trey-nash/3-c#-syntax-overview/README.md
> +- Пространства имен
Because in the original book (paper) the letter **'ё'** is undeservedly not used.

2022-10-27 06:52 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/README.md
> +# Chapter 5. Interfaces and contracts[^1]
What's wrong with Chapter 5? 
(this was a previous commit)

2022-10-27 06:58 UTC, fedotkin commented on trey-nash/6-overloading-operators/README.md
> +- Типы и форматы перегруженных операций
Stupid paragraph title, so excluded, but if necessary, then added.

fixed

2022-10-27 11:16 UTC, raman-m commented on trey-nash/3-c#-syntax-overview/README.md
> +- Пространства имен
Потому что при печати книг в печатном станке, а точнее в матрице для печати сложно следить за введением знака Ё в строку матрицы, поэтому рабочие халявят с вёрсткой знака Ё через набор знака Е в матрицу! Вот почему в русско-язычных книгах часто отсутствует Ё вообще, и правила здесь не причём! Раз есть такая буква в алфавите, то и должна использоваться везде! ☝️

2022-10-27 11:28 UTC, raman-m commented on trey-nash/5-interfaces-and-contracts/README.md
> +# Chapter 5. Interfaces and contracts[^1]
There is mistake in previous commit. It should be fixed!
Using the `.` sign is wrong! In English book all chapter titles are printed with `:` sign.
And all other chapters in Readme use the `:` sign too.
For example: `Chapter 5: Interfaces and Contracts`

2022-10-27 11:37 UTC, raman-m requested changes
Missed `p` in the `Chapter` word for chapters 14-17!
Please, fix it and fix 2 old issues too.

2022-10-27 11:37 UTC, raman-m commented on trey-nash/14-extension-methods/README.md
> +# Chaper 14: Extension Methods
Missed `p` in the `Chapter` word!
It should be: "Cha**p**ter 14"

2022-10-27 11:37 UTC, raman-m commented on trey-nash/15-lambda-expressions/README.md
> +# Chaper 15: Lambda Expressions
Missed `p` in the `Chapter` word!
It should be: "Cha**p**ter 15"

2022-10-27 11:37 UTC, raman-m commented on trey-nash/16-linq-language-integrated-query/README.md
> +# Chaper 16: LINQ: Language Integrated Query
Missed `p` in the `Chapter` word!
It should be: "Cha**p**ter 16"

2022-10-27 11:37 UTC, raman-m commented on trey-nash/17-dynamic-types/README.md
> +# Chaper 17: Dynamic Types
Missed `p` in the `Chapter` word!
It should be: "Cha**p**ter 17"

2022-10-27 12:27 UTC, fedotkin commented on trey-nash/5-interfaces-and-contracts/README.md
> +# Chapter 5. Interfaces and contracts[^1]
fixed

2022-10-27 12:28 UTC, fedotkin commented on trey-nash/3-c#-syntax-overview/README.md
> +- Пространства имен
fixed

2022-10-27 12:32 UTC, fedotkin commented on trey-nash/14-extension-methods/README.md
> +# Chaper 14: Extension Methods
fixed

2022-10-27 12:33 UTC, fedotkin commented on trey-nash/15-lambda-expressions/README.md
> +# Chaper 15: Lambda Expressions
fixed

2022-10-27 12:33 UTC, fedotkin commented on trey-nash/16-linq-language-integrated-query/README.md
> +# Chaper 16: LINQ: Language Integrated Query
fixed

2022-10-27 12:33 UTC, fedotkin commented on trey-nash/17-dynamic-types/README.md
> +# Chaper 17: Dynamic Types
fixed

2022-10-30 15:56 UTC, raman-m approved these changes
Looks perfect! You can do a merge!
Please, use **Rebase and merge** option while merging this PR!!!

2022-10-31 07:03 UTC, merged