#4 Root folder workarounds
fedotkin/dotnet pull request #8
Opened 2022-10-27 10:42 UTC by fedotkin

Root folder looks not good!
Now it's good )

2022-10-27 12:51 UTC, raman-m requested changes
You have to fix the issues. So, the file changes can be better. 😸

2022-10-27 12:51 UTC, raman-m commented on README.md
> +# "dotnet" repository
No need to point that this is repository.
`The 'dotnet' Lab: .NET, C#` is short and informative. Repo title should be short without parasite words like 'repository'.

2022-10-27 12:51 UTC, raman-m commented on README.md
> +---
Please remove this long Horizontal Line markup.
Instead of it you need to paste logo of the .NET, to do that use this SVG graphics: [File:Microsoft .NET logo.svg](https://en.wikipedia.org/wiki/File:Microsoft_.NET_logo.svg).
Consider copying the file to 'assets' branch as resource file and reuse the file from this branch.
See example, Readme in my React repo: [React](https://github.com/raman-m/react)

2022-10-27 12:51 UTC, raman-m commented on README.md
> +This repository created by Alex and Roman to study .NET Framework and C#.
Remove my name and whole string, please. I don't like it!
The fact about studying is OK. But let's make it better.

Put this markup of the About section:
```markdown
## About
Learning laboratory for .NET Framework and C# language. Researches, books, coding challenges, small projects.
```

2022-10-27 12:51 UTC, raman-m commented on README.md
> +## .NET Framework
Where did you take materials from, to copy-paste for **.NET Framework**?

2022-10-27 12:51 UTC, raman-m commented on README.md
> +## C#
Where did you take materials from, to copy-paste for **C#**?
What is the link?

2022-10-27 12:51 UTC, raman-m commented on README.md
> +What the [Wikipedia](https://en.wikipedia.org/wiki/.NET_Framework) says.
Pretty free referencing of Wiki! 😆 
So, I advise to use [Footnotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes) approach from [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

2022-10-27 12:51 UTC, raman-m commented on README.md
> +What the [Wikipedia](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) says.
Please, **use** [Footnotes](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes) approach from [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

2022-10-27 13:32 UTC, fedotkin commented on README.md
> +# "dotnet" repository
fixed

2022-10-27 13:58 UTC, fedotkin commented on README.md
> +## .NET Framework
[туть](https://www.c-sharpcorner.com/article/what-is-c-sharp/)

2022-10-27 13:59 UTC, fedotkin commented on README.md
> +## C#
[туть](https://www.c-sharpcorner.com/article/what-is-c-sharp/)

2022-10-27 14:15 UTC, fedotkin commented on .gitignore
> +*.sln.iml
fixed

2022-10-27 14:15 UTC, fedotkin commented on README.md
> +This repository created by Alex and Roman to study .NET Framework and C#.
fixed

2022-10-28 06:04 UTC, fedotkin commented on README.md
> +---
Fixed, but need to check JS

2022-10-28 08:55 UTC, fedotkin commented on README.md
> +What the [Wikipedia](https://en.wikipedia.org/wiki/.NET_Framework) says.
fixed

2022-10-28 08:55 UTC, fedotkin commented on README.md
> +What the [Wikipedia](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) says.
fixed

2022-10-30 16:07 UTC, raman-m commented on README.md
> +## .NET Framework
OK. But you don't reference this Microsoft page in the foot notes!

2022-10-30 16:19 UTC, raman-m commented on README.md
> +## C#
Using of C-SharpCorner website is not good!
Could you consider to reuse quotes of official Microsoft pages or Wikipedia only!

2022-10-30 16:26 UTC, raman-m requested changes

2022-10-30 16:26 UTC, raman-m commented on README.md
> +
Do NOT use single quotes `'` for HTML-attributes in markup code!
  You have to use double quotes `"` in HTML code!
  For example:
```html
<img src="https://github.com" height="100" alt=".NET Logo" />
```

2022-10-30 16:30 UTC, raman-m commented on README.md
> +---
It seems the images are broken!
Using of root folder of master-branch is not good too... To be discussed...

2022-10-31 07:36 UTC, fedotkin commented on README.md
> +## C#
fixed

2022-10-31 07:36 UTC, fedotkin commented on README.md
> +## .NET Framework
fixed

2022-10-31 07:51 UTC, fedotkin commented on README.md
> +---
fixed

2022-10-31 07:52 UTC, fedotkin commented on README.md
> +
fixed

2022-11-02 20:00 UTC, raman-m approved these changes
Let's merge this version of the code and will see...
Note: This PR should merge to master branch. I've changed base branch as master. After rebasing the branch onto master it has some resolved conflicts. They are happen because of wrong chaining from **dev** branch.
So, the rest of the work for #4 should be done in the next PR.

2022-11-02 20:04 UTC, merged