#86 HackerRank | Algorithms > Strings > Caesar Cipher
fedotkin/dotnet pull request #87
Opened 2023-10-20 12:19 UTC by fedotkin

Task [Caesar Cipher](https://www.hackerrank.com/challenges/caesar-cipher-1/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-10-21 11:18 UTC, raman-m requested changes
Вельмі доўгі алгарытм з непатрэбнымі і вялізнымі адгалінаваннямі канструкцый `if`!
Я мяркую, што адным цыклам `for` і 2-3 радка кода могуць рэалізаваць алгарытм.
Парада: Зрабі азначэнне алфавіта так:
```c#
const string originalAlphabet = "abcdefghijklmnopqrstuvwxyz";
char letter = originalAlphabet[3]; // выкарыстоўвай індэксатар для `string`!
```
Далей сам дадумаеш...

2023-10-21 11:18 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Caesar Cipher.cs
> +            if ('a' <= item & item <= 'z')
Is that definition of Original alphabet?

2023-10-21 11:18 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Caesar Cipher.cs
> +        string result = "";
Гэта зусім непрадукцыйга, бо зклейванне радка з простых адзінак - гэта вельмі дрэнна.
Ты павінен адразу стварыць блок у памяці як масіў `char` або `result` даўжыні `s.Length`
Або карыстацца `StringBuilder`, які аптымізаваны пад аперацыі з радкамі.
Хто не чытае Трэя Нэша, той піша па-джуноўску! 😉 
Раздзел 8: [Working with Strings](https://github.com/fedotkin/dotnet/blob/master/trey-nash/8-working-with-strings/README.md)

2023-10-23 14:04 UTC, raman-m commented
Прыкруці `StringBuilder`! А то вывучыў толькі `string + string` ды `string.Concat()`...

2023-10-23 14:14 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Caesar Cipher.cs
> +        string result = "";
> `char[] result = new char[s.Length];`

Ужопалепей!

2023-10-24 07:49 UTC, fedotkin commented
Не зразумеу...
```c#
result[i] = coded;
```
індэксатару string.this[int] нельга прызначыць - ён даступны толькі для чытання

2023-10-24 14:12 UTC, raman-m commented
>@fedotkin commented [on Oct 24](#issuecomment-1776697990)
індэксатару `string.this[int]` нельга прызначыць - ён даступны толькі для чытання

Правільна! Выкарыстоўвай толькі чытанне. Тады трэба ствараць масіў `char`, як ты і зрабіў:
```c#
var result = new char[s.Length];
```
каб з'явілася магчымасць запісваць індэксатарам. Але можна стварыць радок і праз  `StringBuilder`.
Спынімся на `new char[s.Length]`

2023-10-24 14:27 UTC, raman-m commented
У мяне атрымалася такая версія, якая працуе і юніт-тэсты будуць зялёныя:
```c#
    public static string CaesarCipher(string s, int k)
    {
        const string originalAlphabet = "abcdefghijklmnopqrstuvwxyz";
        var encrypting = new char[s.Length];
        for (int i = 0; i < s.Length; i++)
        {
            encrypting[i] = CipherShift(originalAlphabet, k, s[i]);
        }
        return new string(encrypting); // result
    }

    private static char CipherShift(string alphabet, int rotation, char letter)
    {
        if (!alphabet.Contains(letter, StringComparison.OrdinalIgnoreCase))
            return letter;

        int length = alphabet.Length;
        int shift = rotation % length;
        int index = alphabet.IndexOf(letter, StringComparison.OrdinalIgnoreCase);
        int position = (index + shift) % length;
        char encrypted = alphabet[position];
        return char.IsUpper(letter) ? char.ToUpper(encrypted) : encrypted;
    }
```
На першы погляд гэтая версія таксама грувасткая, але я пакінуў зменныя, каб ты змог прачытаць і зразумець гэтую версію. Ты можаш паспрабаваць сціснуць яе, гэта і будзе тваё заданне.
Я мяркую можна сціснуць да 3-4 радкоў унутры цыкла... Паспрабуй! 😉

2023-10-24 14:45 UTC, raman-m requested changes
Нажаль твая рэалізацыя працуе для асобнага выпадку ўпарадкаванага алфавіту.
А што будзе, калі алфавіт будзе іншы?
А што будзе, калі даўжыня алфавіта зменіцца, напрыклад дадаць або выкінуць сімвалы?

2023-10-24 14:45 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Caesar Cipher.cs
> +                var cipher = (char)(s[i] + k % 26);
Я зразумеў тваю ідэю каб зрушыцца па коду сімвала, але гэта будзе працаваць толькі для упарадкаванага алфавіту, як `abcdefghijklmnopqrstuvwxyz`.

Ты перамяшай сімвалы алфавіта, 2-3 перастаноўкі хопіць, і твая рэалізацыя паляціць, усе модульныя тэсты пачырванеюць...
Але твой падыход норм для упарадкаванага алфафіту табліцы [ASCII](https://en.wikipedia.org/wiki/ASCII)

2023-10-25 11:21 UTC, raman-m requested changes
Адшліфуемся? 😉

2023-10-25 11:21 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Caesar Cipher.cs
> +            }
```suggestion
            int index = alphabet.IndexOf(s[i], StringComparison.OrdinalIgnoreCase);
            char symbol = alphabet[(index + k % length) % length];
            encrypting[i] = char.IsUpper(s[i]) ? char.ToUpper(symbol) : symbol;
```
Так чытаецца лепш.

2023-10-25 12:07 UTC, raman-m approved these changes

2023-10-25 12:15 UTC, merged