#88 HackerRank | Algorithms > Implementation > Between Two Sets
fedotkin/dotnet pull request #89
Opened 2023-10-26 11:10 UTC by fedotkin

Task [Between Two Sets](https://www.hackerrank.com/challenges/between-two-sets/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-10-26 15:28 UTC, raman-m reviewed
Жэстачайшы алгарытм! 
Юніты хоць зялёныя? 🤣

2023-10-26 15:28 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        }
```suggestion
        using System.Linq;
        maxValue = a.Max();
```

2023-10-26 15:28 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        }
```suggestion
        int bMax = b.Max();
        maxValue = Math.Max(maxValue, bMax);
```

2023-10-26 15:28 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        List<List<int>> numbers = new List<List<int>>();
```suggestion
        var numbers = new List<List<int>>();
```

2023-10-27 08:58 UTC, fedotkin commented
Згодны, алгарытм жэстачайшы, разумею, што два укладзеныя форы гэта занадта грувастка, але у часавы ліміт праграма укладваецца.
Вось такі джунні код)
А так, усе тэсты, вядома, зялёныя.

2023-10-27 09:45 UTC, raman-m requested changes
Шліфуй алгарытм, джунні-патрыёт! 😉

2023-10-27 09:45 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        int maxValue = Math.Max(a.Max(), b.Max());
```suggestion
        if (a?.Any() == false || b?.Any() == false) // масівы пустыя без элементаў
            return 0; // уваходныя параметры не прайшлі праверку
        // іншыя праверкі масіваў
        int max = int.Max(a.Max(), b.Max()); // назва можа быць і карацей
```

2023-10-27 09:45 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        for (int i = 0; i < b.Count; i++)
Мяркую, што два цыкла for можна зліць у адзін: вельмі падобныя целы двух цыклаў. Паспрабуй

2023-10-27 09:45 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +            foreach (var item in numbers[i])
item не чытаецца! Што за item?
```suggestion
            foreach (int denominator in numbers[i])
```
і не хавай тыпы па значэнню (value types) пад `var`, які больш пасуе пад доўгія тыпы па спасылцы (reference types).

2023-10-27 09:51 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        int maxValue = Math.Max(a.Max(), b.Max());
Сэнс такі: `if (a == null || b == null || a.Count == 0 || b.Count == 0)`

2023-10-27 10:56 UTC, fedotkin commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        for (int i = 0; i < b.Count; i++)
Не атрымаецца, гэты алгарытм уладкованы так, што перабор "b" пачынаецца з выніковымі дадзенымі пасля перабору "a".
Напэуна можна абыйсціся адным форам у алгарытме з іншым прынцыпам, але джуноускага мозгу хапіла на выдумку толькі аднаго алгарытма.
Прапаную перайсці да новай, цікавейшай задачы)

2023-10-27 17:30 UTC, raman-m commented on hackerrank/src/Algorithms/Implementation/BetweenTwoSets.cs
> +        for (int i = 0; i < b.Count; i++)
Прапаную пафіксіць код рэвью!...
А то пойдзеш касіць снег пад вокнамі арганізацыі ))

2023-10-27 17:36 UTC, raman-m approved these changes
У масіваў `a` і `b` могуць быць рознай даўжыні, то не атрымаецца адным цыклам.
Даю дазвол на мэрдж.

2023-10-29 08:11 UTC, merged