#92 HackerRank | Algorithms > Strings > Anagram
fedotkin/dotnet pull request #93
Opened 2023-10-30 12:19 UTC by fedotkin

Task [Anagram](https://www.hackerrank.com/challenges/anagram/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-10-30 20:18 UTC, raman-m requested changes
Джунні, фіксі!

2023-10-30 20:18 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Anagram.cs
> +    public static int anagram(string s)
```suggestion
    public static int Anagram(string s)
```
Не пішы з маленькай літары! У СіШарп усе назвы звычайна пычынаецца з вялікай літары, больш вядома як PascalCase

2023-10-30 20:18 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Anagram.cs
> +        second.AddRange(s.Substring(s.Length / 2, s.Length / 2).ToCharArray());
```suggestion
        var second = s.Substring(s.Length / 2, s.Length / 2).ToList();
```
🤣 Ай, Лёша, джун!

2023-10-31 07:20 UTC, fedotkin commented on hackerrank/src/Algorithms/Strings/Anagram.cs
> +        second.AddRange(s.Substring(s.Length / 2, s.Length / 2).ToCharArray());
ну блін, нагарадзіу канструкцыю)
адчувау жа, што можна прасцей

2023-10-31 12:09 UTC, raman-m requested changes
Адшліфуемся?

2023-10-31 12:09 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/Anagram.cs
> +        var second = s.Substring(s.Length / 2, s.Length / 2).ToList();
```suggestion
        int length = s.Length / 2;
        string first = s.Substring(0, length);
        var second = s.Substring(length, length).ToList();
```

2023-11-01 08:54 UTC, fedotkin commented
шлiфануу

2023-11-01 10:12 UTC, merged