#94 HackerRank | Algorithms > Strings > Palindrome Index
fedotkin/dotnet pull request #95
Opened 2023-11-01 12:36 UTC by fedotkin

Task [Palindrome Index](https://www.hackerrank.com/challenges/palindrome-index/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-11-01 12:42 UTC, fedotkin commented
Няпростая задача аднак.
Першая версія алгарытму не мінула ліміт часу!
Прыйшлося падумаць і стварыць новую версію алгарытму. 
Бягучая версія прайшла ліміт і ўсе тэсты зялёныя.

2023-11-02 10:59 UTC, raman-m requested changes
Джун, табе салют! 😄

2023-11-02 10:59 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/PalindromeIndex.cs
> +        int length = s.Length;
```suggestion
        if (string.IsNullOrEmpty(s))
            return -1;

        var list = new List<char>(s);
        int index = -1;
        int length = list.Count;
```

2023-11-02 10:59 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/PalindromeIndex.cs
> +                test = s.Remove(i, 1);
Гэта цяжкое дзеянне па выдаленню сімвала з радка! Ня дзіва, што твая першая рэалізацыя заваліла модульныя тэсты.
Я прапаную стварыць спіс `char` і рабіць дзеянні над спісам, бо ў цябе вельмі шмат выдаленняў.
```C#
list.RemoveAt(i);
```
Запамятай, дзеянні па дадаванню або выдаленню ў такіх тыпах як `string`, `char[]` вельмі цяжкія, бо ідзе высокая нагрузка на аператыўную памяць і працэсар.
Найлепшы выбар тут - гэта `List<char>`.

2023-11-02 10:59 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/PalindromeIndex.cs
> +            if (test[i] != test[length - 2 - i])
```suggestion
            if (list[i] != list[length - 2 - i])
```
Мяркую, што можна абыйсціся без дадатковай зменнай `test`, бо хопіць і адной `list`

2023-11-02 10:59 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/PalindromeIndex.cs
> +            if (s[i] != s[length - 1 - i])
```suggestion
            if (list[i] != list[length - 1 - i])
```

2023-11-02 10:59 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/PalindromeIndex.cs
> +        for (int i = 0; i < (length - 1) / 2; i++)
Можа гэты другі праход лішні?
Можа верхні **for** можна абгарнуць у **while** ?

2023-11-03 11:33 UTC, fedotkin commented
Пазбавіуся ад другога фора.
Пасля выдалення з ліста, досыць параунаць парныя сiмвалы з бягучым iндэксам.
Таксама трэба праверыць парныя сiмвалы з наступным індэксам (дадау тэст для такога цікавага выпадку: "ab88b8a")

2023-11-03 16:56 UTC, raman-m requested changes
А тэсты ўсе зялёныя?

2023-11-03 16:56 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/PalindromeIndex_ResultTests.cs
> +    public void StringConstruction_LetterIndex(string text, int expected)
```suggestion
    public void PalindromeIndex_HappyPath(string text, int expected)
```

2023-11-04 06:34 UTC, fedotkin commented
так, тэсты зялёныя

2023-11-04 08:18 UTC, raman-m approved these changes

2023-11-05 10:43 UTC, merged