#98 HackerRank | Algorithms > Strings > Weighted Uniform Strings
fedotkin/dotnet pull request #99
Opened 2023-11-13 14:02 UTC by fedotkin

Task [Weighted Uniform Strings](https://www.hackerrank.com/challenges/weighted-uniform-string/problem)
Profile [@alexei_fedotkin](https://www.hackerrank.com/alexei_fedotkin)

2023-11-13 14:35 UTC, raman-m requested changes
Джун, я разпілаваў твой мега-алгарытм на часткі! :grin:

2023-11-13 14:35 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        const string alphabet = "abcdefghijklmnopqrstuvwxyz";
```suggestion
        const string alphabet = "abcdefghijklmnopqrstuvwxyz";
        if (string.IsNullOrEmpty(s) || queries?.Count == 0)
            return new();
            
```

2023-11-13 14:35 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        List<int> weightList = new List<int>();
```suggestion
        var result = new List<string>();
        var weightList = new List<int>();
```

2023-11-13 14:35 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +                result.Add("No");
```suggestion
            result.Add(weightList.Contains(queries[i]) ? "Yes" : "No");
```

2023-11-13 14:35 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        for (int i = 0; i < length; i++)
```suggestion
        for (int i = 0; i < length; i++, weight++)
```

2023-11-13 14:35 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +                weight++;
```suggestion
            if (s[i] != s[i + 1])
                weight = 0;
```

2023-11-13 14:54 UTC, raman-m requested changes
Накіну яшчэ на вентылятар...🤣
І перарабі 3 факты ў адну тэорыю!

2023-11-13 14:54 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +{
```suggestion
public class Result
{
    public const string No = nameof(No);
    public const string Yes = nameof(Yes);

```

2023-11-13 14:54 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/WeightedUniformStrings_ResultTests.cs
> +{
```suggestion
public class WeightedUniformStrings_ResultTests
{
    private const string No = Result.No;
    private const string Yes = Result.Yes;
```

2023-11-13 14:54 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/WeightedUniformStrings_ResultTests.cs
> +        List<string> expected = new List<string>() { "Yes", "No", "No", "Yes", "No" };
```suggestion
        var text = "abbcccdddd";
        var queries = new List<int> { 1, 7, 5, 4, 15 };
        var expected = new List<string> { Yes, No, No, Yes, No };
```

2023-11-13 14:54 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/WeightedUniformStrings_ResultTests.cs
> +        List<string> expected = new List<string>() { "Yes", "Yes", "Yes", "Yes", "No", "No" };
```suggestion
        var text = "abccddde";
        var queries = new List<int> { 1, 3, 12, 5, 9, 10 };
        var expected = new List<string>() { Yes, Yes, Yes, Yes, No, No };
```

2023-11-13 14:54 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/WeightedUniformStrings_ResultTests.cs
> +        List<string> expected = new List<string>() { "Yes", "No", "Yes", "Yes", "No" };
```suggestion
        var text = "aaabbbbcccddd";
        var queries = new List<int> { 9, 7, 8, 12, 5 };
        var expected = new List<string> { Yes, No, Yes, Yes, No };
```

2023-11-14 08:25 UTC, fedotkin commented
Усё пафіксіу, такі да, алгарытм стау лепш 👍
Не змог перарабіць 3 факты у 1 тэорыю, пачатковыя дадзеныя - гэта спіскi рознай даужыні (

2023-11-14 09:58 UTC, raman-m requested changes
Адшліфуемся? :satisfied:
Грызі граніт навукі, джун! :grin:

2023-11-14 09:58 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        for (int i = 0; i < length; i++, weight++)
```suggestion
        for (int i = 0; i <= length; i++, weight++)
```

2023-11-14 09:58 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +            weightList.Add(weight * (alphabet.IndexOf(s[i]) + 1));
```suggestion
            values.Add(weight * (alphabet.IndexOf(s[i]) + 1));
```

2023-11-14 09:58 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +            if (s[i] != s[i + 1])
```suggestion
            if (i < length && s[i] != s[i + 1])
```

2023-11-14 09:58 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        weightList.Add(weight * (alphabet.IndexOf(s[length]) + 1));
Гэты радок кода за межамі цыкла ўжо непатрэбны.

2023-11-14 09:58 UTC, raman-m commented on hackerrank/src/Algorithms/Strings/WeightedUniformStrings.cs
> +        return result;
```suggestion
        return queries // LINQ to Objects >>>
            .Select(item => values.Contains(item) ? Yes : No)
            .ToList();
```

2023-11-14 09:58 UTC, raman-m commented on hackerrank/test/Algorithms/Strings/WeightedUniformStrings_ResultTests.cs
> +    }
Вось так можна перарабіць тры факты ў адну тэорыю:
```suggestion
    static List<object[]> WeightedUniformStrings_TestData = new List<object[]>
    {
        new object[] { "Example", "abbcccdddd", new List<int>() { 1, 7, 5, 4, 15 }, new List<string>() { Yes, No, No, Yes, No } },
        new object[] { "Sample0", "abccddde", new List<int>() {1, 3, 12, 5, 9, 10 }, new List<string>() { Yes, Yes, Yes, Yes, No, No } },
        new object[] { "Sample1", "aaabbbbcccddd", new List<int>() { 9, 7, 8, 12, 5 }, new List<string>() {  Yes, No, Yes, Yes, No } },
    };

    [Theory]
    [InlineData("Example")]
    [InlineData("Sample0")]
    [InlineData("Sample1")]
    public void WeightedUniformStrings_AllSamples_HappyPath(string testName)
    {
        // Arrange
        int index = WeightedUniformStrings_TestData.FindIndex(x => testName == (string)x.First());
        if (index == -1) throw new KeyNotFoundException();
        var text = WeightedUniformStrings_TestData[index][1] as string;
        var queries = WeightedUniformStrings_TestData[index][2] as List<int>;
        var expected = WeightedUniformStrings_TestData[index][3] as List<string>;

        // Act
        var actual = WeightedUniformStrings(text, queries);

        // Assert
        Assert.Equal(expected, actual);
    }
```

2023-11-14 11:09 UTC, fedotkin commented
Цiкава аднак 🥇

2023-11-14 11:32 UTC, raman-m approved these changes

2023-11-14 12:21 UTC, merged